export const PAYMENT_STATUS_PENDING = 1;
export const PAYMENT_STATUS_COMPLETED = 2;
export const PAYMENT_STATUS_FAILED = 3;

export const PAYMENT_METHOD_CASH = 1;
export const PAYMENT_METHOD_CARD = 2;
export const PAYMENT_METHOD_MOBILE = 3;
export const PAYMENT_METHOD_BAKONG_QRCODE = 4;